name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Shiny App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e "install.packages('shiny')"
          R -e "install.packages('testthat')"

      - name: Run Shiny app
        run: |
          R -e "shiny::runApp('app.R', launch.browser = FALSE)"
      - name: Stop Shiny app #Kill the R process running the Shiny App
        run: |
          pkill -f "R -e shiny::runApp"
          echo "Shiny app stopped."
